// presentation v2 — icon catalog access (Lucide, ISC).
//
//   node icons.cjs --list                 # names, comma separated
//   node icons.cjs --get rocket funnel    # paste-ready <svg class="icon" …> lines
//   node icons.cjs --catalog [path]       # regenerate styles/_base/icons.md
//
// Source SVGs live in styles/_base/icons/ (lucide-static, ISC — see
// vendor/LICENSE-lucide.txt). The catalog file is generated from these files,
// so names in the docs and the helper can never drift.
"use strict";

const fs = require("fs");
const path = require("path");

const DIR = path.join(__dirname, "..", "styles", "_base", "icons");

function listIcons() {
  if (!fs.existsSync(DIR)) return [];
  return fs
    .readdirSync(DIR)
    .filter((f) => f.endsWith(".svg"))
    .map((f) => f.replace(/\.svg$/, ""))
    .sort();
}

function iconLine(name) {
  const file = path.join(DIR, name + ".svg");
  if (!fs.existsSync(file)) return null;
  const raw = fs.readFileSync(file, "utf8");
  const inner = raw
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>[\s\S]*$/, "");
  const body = inner.replace(/\s+/g, " ").replace(/>\s+</g, "><").trim();
  return (
    '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" ' +
    'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' + body + "</svg>"
  );
}

function catalog(outPath) {
  const names = listIcons();
  const lines = [
    "# Icons (Lucide, ISC) — paste-ready",
    "",
    "Generated by `icons.cjs --catalog`. One `<svg class=\"icon\">` per name;",
    "stroke is `currentColor` (inherits the parent color, e.g. the accent token).",
    "Use at most one icon per card heading; never as bullet decoration.",
    "",
    `${names.length} icons.`,
    "",
  ];
  for (const name of names) {
    const line = iconLine(name);
    if (!line) continue;
    lines.push(`## ${name}`, "", "```html", line, "```", "");
  }
  const target = outPath || path.join(DIR, "..", "icons.md");
  fs.writeFileSync(target, lines.join("\n"));
  return { count: names.length, target };
}

function main() {
  const argv = process.argv.slice(2);
  if (argv.includes("--list")) {
    const names = listIcons();
    console.log(names.join(", "));
    console.log("(" + names.length + " icons; catalog: styles/_base/icons.md)");
    return;
  }
  if (argv.includes("--catalog")) {
    const idx = argv.indexOf("--catalog");
    const out = argv[idx + 1] && !argv[idx + 1].startsWith("--") ? argv[idx + 1] : null;
    const res = catalog(out);
    console.log("catalog: " + res.target + " (" + res.count + " icons)");
    return;
  }
  const getIdx = argv.indexOf("--get");
  const names = getIdx !== -1 ? argv.slice(getIdx + 1) : argv.filter((a) => !a.startsWith("--"));
  if (!names.length) {
    console.error("usage: icons.cjs --list | --get <name> [name…] | --catalog [path]");
    process.exit(2);
  }
  let failed = 0;
  for (const n of names) {
    const line = iconLine(n);
    if (!line) {
      console.error("unknown icon: " + n);
      failed++;
      continue;
    }
    console.log(line);
  }
  if (failed) process.exit(1);
}

if (require.main === module) main();

module.exports = { listIcons, iconLine, catalog, DIR };
